#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 173
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LT = 2,
  anon_sym_SLASH_GT = 3,
  anon_sym_GT = 4,
  anon_sym_LT_SLASH = 5,
  anon_sym_u25ca = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_EQ = 11,
  sym_text = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  anon_sym_SQUOTE = 15,
  aux_sym_string_token2 = 16,
  anon_sym_SEMI = 17,
  aux_sym_comment_token1 = 18,
  sym_source_file = 19,
  sym__expression = 20,
  sym_tag = 21,
  sym_command = 22,
  sym_bracket_args = 23,
  sym_brace_args = 24,
  sym_lozenge_command = 25,
  sym_attribute = 26,
  sym_string = 27,
  sym_comment = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_tag_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_u25ca] = "\u25ca",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [sym_text] = "text",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_SEMI] = ";",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_tag] = "tag",
  [sym_command] = "command",
  [sym_bracket_args] = "bracket_args",
  [sym_brace_args] = "brace_args",
  [sym_lozenge_command] = "lozenge_command",
  [sym_attribute] = "attribute",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_u25ca] = anon_sym_u25ca,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_text] = sym_text,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_tag] = sym_tag,
  [sym_command] = sym_command,
  [sym_bracket_args] = sym_bracket_args,
  [sym_brace_args] = sym_brace_args,
  [sym_lozenge_command] = sym_lozenge_command,
  [sym_attribute] = sym_attribute,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u25ca] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_args] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_args] = {
    .visible = true,
    .named = true,
  },
  [sym_lozenge_command] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 3,
  [10] = 4,
  [11] = 2,
  [12] = 3,
  [13] = 13,
  [14] = 5,
  [15] = 5,
  [16] = 6,
  [17] = 2,
  [18] = 13,
  [19] = 19,
  [20] = 8,
  [21] = 4,
  [22] = 4,
  [23] = 5,
  [24] = 24,
  [25] = 8,
  [26] = 24,
  [27] = 3,
  [28] = 19,
  [29] = 8,
  [30] = 24,
  [31] = 13,
  [32] = 19,
  [33] = 13,
  [34] = 2,
  [35] = 24,
  [36] = 19,
  [37] = 13,
  [38] = 6,
  [39] = 19,
  [40] = 24,
  [41] = 6,
  [42] = 2,
  [43] = 43,
  [44] = 43,
  [45] = 43,
  [46] = 43,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 56,
  [58] = 55,
  [59] = 50,
  [60] = 54,
  [61] = 51,
  [62] = 62,
  [63] = 63,
  [64] = 47,
  [65] = 52,
  [66] = 62,
  [67] = 51,
  [68] = 47,
  [69] = 54,
  [70] = 63,
  [71] = 71,
  [72] = 53,
  [73] = 71,
  [74] = 71,
  [75] = 48,
  [76] = 49,
  [77] = 62,
  [78] = 63,
  [79] = 56,
  [80] = 52,
  [81] = 48,
  [82] = 51,
  [83] = 49,
  [84] = 54,
  [85] = 55,
  [86] = 56,
  [87] = 53,
  [88] = 50,
  [89] = 71,
  [90] = 55,
  [91] = 49,
  [92] = 62,
  [93] = 63,
  [94] = 47,
  [95] = 52,
  [96] = 53,
  [97] = 50,
  [98] = 48,
  [99] = 99,
  [100] = 99,
  [101] = 99,
  [102] = 99,
  [103] = 103,
  [104] = 103,
  [105] = 105,
  [106] = 105,
  [107] = 107,
  [108] = 103,
  [109] = 103,
  [110] = 105,
  [111] = 105,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 115,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 53,
  [123] = 119,
  [124] = 124,
  [125] = 125,
  [126] = 115,
  [127] = 118,
  [128] = 119,
  [129] = 120,
  [130] = 121,
  [131] = 131,
  [132] = 132,
  [133] = 118,
  [134] = 134,
  [135] = 125,
  [136] = 120,
  [137] = 118,
  [138] = 119,
  [139] = 139,
  [140] = 140,
  [141] = 115,
  [142] = 125,
  [143] = 143,
  [144] = 125,
  [145] = 145,
  [146] = 140,
  [147] = 124,
  [148] = 143,
  [149] = 116,
  [150] = 145,
  [151] = 140,
  [152] = 124,
  [153] = 143,
  [154] = 116,
  [155] = 145,
  [156] = 140,
  [157] = 124,
  [158] = 158,
  [159] = 121,
  [160] = 50,
  [161] = 145,
  [162] = 48,
  [163] = 158,
  [164] = 49,
  [165] = 165,
  [166] = 116,
  [167] = 143,
  [168] = 158,
  [169] = 169,
  [170] = 121,
  [171] = 158,
  [172] = 120,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 29,
        '\'', 32,
        '/', 7,
        ';', 35,
        '<', 12,
        '=', 23,
        '>', 15,
        '[', 18,
        ']', 19,
        '{', 20,
        '}', 21,
        0x25ca, 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\'') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '>') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 3:
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == 0x25ca) ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == 0x25ca) ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != ']') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == 0x25ca) ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '>') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(13);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == 0x25ca) ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(28);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_u25ca);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == 0x25ca) ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == 0x25ca) ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != ']') ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == 0x25ca) ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == 0x25ca) ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != 0x25ca) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 8},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 8},
  [71] = {.lex_state = 8},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 8},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 8},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 4},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 4},
  [95] = {.lex_state = 4},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 4},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 6},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 6},
  [118] = {.lex_state = 6},
  [119] = {.lex_state = 6},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 36},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 6},
  [124] = {.lex_state = 1},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 6},
  [127] = {.lex_state = 6},
  [128] = {.lex_state = 6},
  [129] = {.lex_state = 1},
  [130] = {.lex_state = 36},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 6},
  [134] = {.lex_state = 33},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 6},
  [138] = {.lex_state = 6},
  [139] = {.lex_state = 30},
  [140] = {.lex_state = 1},
  [141] = {.lex_state = 6},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 1},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 1},
  [146] = {.lex_state = 1},
  [147] = {.lex_state = 1},
  [148] = {.lex_state = 1},
  [149] = {.lex_state = 1},
  [150] = {.lex_state = 1},
  [151] = {.lex_state = 1},
  [152] = {.lex_state = 1},
  [153] = {.lex_state = 1},
  [154] = {.lex_state = 1},
  [155] = {.lex_state = 1},
  [156] = {.lex_state = 1},
  [157] = {.lex_state = 1},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 36},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 1},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 6},
  [166] = {.lex_state = 1},
  [167] = {.lex_state = 1},
  [168] = {.lex_state = 0},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 36},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_u25ca] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(169),
    [sym__expression] = STATE(7),
    [sym_tag] = STATE(7),
    [sym_command] = STATE(7),
    [sym_lozenge_command] = STATE(7),
    [sym_comment] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_u25ca] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_text] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    STATE(39), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [27] = 7,
    ACTIONS(27), 1,
      anon_sym_LT,
    ACTIONS(30), 1,
      anon_sym_u25ca,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      sym_text,
    ACTIONS(41), 1,
      anon_sym_SEMI,
    STATE(3), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [54] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(46), 1,
      anon_sym_LT_SLASH,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [81] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(56), 1,
      anon_sym_LT_SLASH,
    ACTIONS(58), 1,
      sym_text,
    STATE(4), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [108] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(60), 1,
      anon_sym_LT_SLASH,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [135] = 7,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_u25ca,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_SEMI,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_text,
    STATE(12), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [162] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(66), 1,
      anon_sym_LT_SLASH,
    ACTIONS(68), 1,
      sym_text,
    STATE(6), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [189] = 7,
    ACTIONS(36), 1,
      anon_sym_RBRACK,
    ACTIONS(70), 1,
      anon_sym_LT,
    ACTIONS(73), 1,
      anon_sym_u25ca,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      sym_text,
    ACTIONS(82), 1,
      anon_sym_SEMI,
    STATE(9), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [216] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(66), 1,
      anon_sym_LT_SLASH,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [243] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(85), 1,
      anon_sym_RBRACK,
    ACTIONS(87), 1,
      sym_text,
    STATE(19), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [270] = 7,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      anon_sym_u25ca,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      sym_text,
    ACTIONS(103), 1,
      anon_sym_SEMI,
    STATE(12), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [297] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    ACTIONS(114), 1,
      sym_text,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    STATE(24), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [324] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(118), 1,
      anon_sym_LT_SLASH,
    ACTIONS(120), 1,
      sym_text,
    STATE(22), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [351] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(122), 1,
      anon_sym_LT_SLASH,
    ACTIONS(124), 1,
      sym_text,
    STATE(10), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [378] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(126), 1,
      anon_sym_LT_SLASH,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [405] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    ACTIONS(130), 1,
      sym_text,
    STATE(28), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [432] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    ACTIONS(134), 1,
      sym_text,
    STATE(30), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [459] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(136), 1,
      anon_sym_RBRACK,
    ACTIONS(138), 1,
      sym_text,
    STATE(9), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [486] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(140), 1,
      anon_sym_LT_SLASH,
    ACTIONS(142), 1,
      sym_text,
    STATE(16), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [513] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(140), 1,
      anon_sym_LT_SLASH,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [540] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(144), 1,
      anon_sym_LT_SLASH,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [567] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(146), 1,
      anon_sym_LT_SLASH,
    ACTIONS(148), 1,
      sym_text,
    STATE(21), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [594] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    ACTIONS(152), 1,
      sym_text,
    STATE(3), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [621] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(144), 1,
      anon_sym_LT_SLASH,
    ACTIONS(154), 1,
      sym_text,
    STATE(38), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [648] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(152), 1,
      sym_text,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    STATE(3), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [675] = 7,
    ACTIONS(36), 1,
      anon_sym_LT_SLASH,
    ACTIONS(158), 1,
      anon_sym_LT,
    ACTIONS(161), 1,
      anon_sym_u25ca,
    ACTIONS(164), 1,
      anon_sym_LBRACE,
    ACTIONS(167), 1,
      sym_text,
    ACTIONS(170), 1,
      anon_sym_SEMI,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [702] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(138), 1,
      sym_text,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    STATE(9), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [729] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(46), 1,
      anon_sym_LT_SLASH,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(175), 1,
      sym_text,
    STATE(41), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [756] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(152), 1,
      sym_text,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    STATE(3), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [783] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    ACTIONS(181), 1,
      sym_text,
    STATE(40), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [810] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(138), 1,
      sym_text,
    ACTIONS(183), 1,
      anon_sym_RBRACK,
    STATE(9), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [837] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(187), 1,
      sym_text,
    STATE(26), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [864] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
    ACTIONS(191), 1,
      sym_text,
    STATE(32), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [891] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(152), 1,
      sym_text,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    STATE(3), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [918] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(138), 1,
      sym_text,
    ACTIONS(195), 1,
      anon_sym_RBRACK,
    STATE(9), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [945] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      sym_text,
    STATE(35), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [972] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(201), 1,
      anon_sym_LT_SLASH,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [999] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(138), 1,
      sym_text,
    ACTIONS(203), 1,
      anon_sym_RBRACK,
    STATE(9), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1026] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_u25ca,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(152), 1,
      sym_text,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    STATE(3), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1053] = 7,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_u25ca,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(207), 1,
      anon_sym_LT_SLASH,
    STATE(27), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1080] = 7,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_u25ca,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_SEMI,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
    ACTIONS(211), 1,
      sym_text,
    STATE(36), 6,
      sym__expression,
      sym_tag,
      sym_command,
      sym_lozenge_command,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1107] = 4,
    ACTIONS(215), 1,
      anon_sym_LBRACK,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(90), 2,
      sym_bracket_args,
      sym_brace_args,
    ACTIONS(213), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      sym_text,
      anon_sym_SEMI,
  [1125] = 4,
    ACTIONS(219), 1,
      anon_sym_LBRACK,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
    STATE(55), 2,
      sym_bracket_args,
      sym_brace_args,
    ACTIONS(213), 5,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      sym_text,
      anon_sym_SEMI,
  [1143] = 4,
    ACTIONS(223), 1,
      anon_sym_LBRACK,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    STATE(85), 2,
      sym_bracket_args,
      sym_brace_args,
    ACTIONS(213), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1161] = 5,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
    ACTIONS(229), 1,
      anon_sym_LBRACK,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
    STATE(58), 2,
      sym_bracket_args,
      sym_brace_args,
    ACTIONS(213), 4,
      anon_sym_LT,
      anon_sym_u25ca,
      sym_text,
      anon_sym_SEMI,
  [1181] = 1,
    ACTIONS(233), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1190] = 1,
    ACTIONS(235), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1199] = 1,
    ACTIONS(237), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1208] = 2,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
    ACTIONS(241), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1219] = 1,
    ACTIONS(243), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1228] = 2,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1239] = 2,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    ACTIONS(251), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1250] = 1,
    ACTIONS(253), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1259] = 1,
    ACTIONS(255), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1268] = 1,
    ACTIONS(257), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1277] = 2,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
    ACTIONS(257), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1288] = 2,
    ACTIONS(261), 1,
      ts_builtin_sym_end,
    ACTIONS(255), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1299] = 1,
    ACTIONS(241), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1308] = 2,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
    ACTIONS(253), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1319] = 2,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
    ACTIONS(243), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1330] = 1,
    ACTIONS(267), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1339] = 1,
    ACTIONS(269), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1348] = 1,
    ACTIONS(233), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1357] = 1,
    ACTIONS(247), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1366] = 2,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    ACTIONS(267), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1377] = 1,
    ACTIONS(243), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1386] = 2,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
    ACTIONS(233), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1397] = 1,
    ACTIONS(253), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1406] = 2,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
    ACTIONS(269), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1417] = 2,
    ACTIONS(277), 1,
      ts_builtin_sym_end,
    ACTIONS(279), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1428] = 1,
    ACTIONS(251), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1437] = 1,
    ACTIONS(279), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1446] = 1,
    ACTIONS(279), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1455] = 1,
    ACTIONS(235), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1464] = 1,
    ACTIONS(237), 6,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1473] = 1,
    ACTIONS(267), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1482] = 1,
    ACTIONS(269), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1491] = 1,
    ACTIONS(257), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1500] = 1,
    ACTIONS(247), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1509] = 2,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
    ACTIONS(235), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1520] = 1,
    ACTIONS(243), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1529] = 2,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
    ACTIONS(237), 5,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1540] = 1,
    ACTIONS(253), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1549] = 1,
    ACTIONS(255), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1558] = 1,
    ACTIONS(257), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1567] = 1,
    ACTIONS(251), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1576] = 1,
    ACTIONS(241), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1585] = 1,
    ACTIONS(279), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1594] = 1,
    ACTIONS(255), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1603] = 1,
    ACTIONS(237), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_SEMI,
  [1612] = 1,
    ACTIONS(267), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1621] = 1,
    ACTIONS(269), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1630] = 1,
    ACTIONS(233), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1639] = 1,
    ACTIONS(247), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1648] = 1,
    ACTIONS(251), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1657] = 1,
    ACTIONS(241), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1666] = 1,
    ACTIONS(235), 6,
      anon_sym_LT,
      anon_sym_u25ca,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_text,
      anon_sym_SEMI,
  [1675] = 4,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(287), 1,
      anon_sym_SLASH_GT,
    ACTIONS(289), 1,
      anon_sym_GT,
    STATE(109), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1689] = 4,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(291), 1,
      anon_sym_SLASH_GT,
    ACTIONS(293), 1,
      anon_sym_GT,
    STATE(108), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1703] = 4,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(295), 1,
      anon_sym_SLASH_GT,
    ACTIONS(297), 1,
      anon_sym_GT,
    STATE(104), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1717] = 4,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(299), 1,
      anon_sym_SLASH_GT,
    ACTIONS(301), 1,
      anon_sym_GT,
    STATE(103), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1731] = 4,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(303), 1,
      anon_sym_SLASH_GT,
    ACTIONS(305), 1,
      anon_sym_GT,
    STATE(107), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1745] = 4,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(307), 1,
      anon_sym_SLASH_GT,
    ACTIONS(309), 1,
      anon_sym_GT,
    STATE(107), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1759] = 4,
    ACTIONS(311), 1,
      anon_sym_LBRACK,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
    STATE(142), 2,
      sym_bracket_args,
      sym_brace_args,
  [1773] = 4,
    ACTIONS(311), 1,
      anon_sym_LBRACK,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
    STATE(144), 2,
      sym_bracket_args,
      sym_brace_args,
  [1787] = 4,
    ACTIONS(319), 1,
      sym_identifier,
    ACTIONS(322), 1,
      anon_sym_SLASH_GT,
    ACTIONS(324), 1,
      anon_sym_GT,
    STATE(107), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1801] = 4,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(326), 1,
      anon_sym_SLASH_GT,
    ACTIONS(328), 1,
      anon_sym_GT,
    STATE(107), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1815] = 4,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(330), 1,
      anon_sym_SLASH_GT,
    ACTIONS(332), 1,
      anon_sym_GT,
    STATE(107), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [1829] = 4,
    ACTIONS(311), 1,
      anon_sym_LBRACK,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
    ACTIONS(334), 1,
      anon_sym_RBRACE,
    STATE(125), 2,
      sym_bracket_args,
      sym_brace_args,
  [1843] = 4,
    ACTIONS(311), 1,
      anon_sym_LBRACK,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
    ACTIONS(336), 1,
      anon_sym_RBRACE,
    STATE(135), 2,
      sym_bracket_args,
      sym_brace_args,
  [1857] = 4,
    ACTIONS(338), 1,
      sym_identifier,
    ACTIONS(340), 1,
      anon_sym_DQUOTE,
    ACTIONS(342), 1,
      anon_sym_SQUOTE,
    STATE(113), 1,
      sym_string,
  [1870] = 2,
    ACTIONS(346), 1,
      anon_sym_SLASH_GT,
    ACTIONS(344), 2,
      anon_sym_GT,
      sym_identifier,
  [1878] = 2,
    ACTIONS(350), 1,
      anon_sym_SLASH_GT,
    ACTIONS(348), 2,
      anon_sym_GT,
      sym_identifier,
  [1886] = 1,
    ACTIONS(352), 1,
      anon_sym_GT,
  [1890] = 1,
    ACTIONS(354), 1,
      sym_identifier,
  [1894] = 1,
    ACTIONS(356), 1,
      anon_sym_GT,
  [1898] = 1,
    ACTIONS(358), 1,
      anon_sym_GT,
  [1902] = 1,
    ACTIONS(360), 1,
      anon_sym_GT,
  [1906] = 1,
    ACTIONS(362), 1,
      sym_identifier,
  [1910] = 1,
    ACTIONS(364), 1,
      aux_sym_comment_token1,
  [1914] = 1,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
  [1918] = 1,
    ACTIONS(366), 1,
      anon_sym_GT,
  [1922] = 1,
    ACTIONS(368), 1,
      sym_identifier,
  [1926] = 1,
    ACTIONS(370), 1,
      anon_sym_RBRACE,
  [1930] = 1,
    ACTIONS(372), 1,
      anon_sym_GT,
  [1934] = 1,
    ACTIONS(374), 1,
      anon_sym_GT,
  [1938] = 1,
    ACTIONS(376), 1,
      anon_sym_GT,
  [1942] = 1,
    ACTIONS(378), 1,
      sym_identifier,
  [1946] = 1,
    ACTIONS(380), 1,
      aux_sym_comment_token1,
  [1950] = 1,
    ACTIONS(382), 1,
      anon_sym_SQUOTE,
  [1954] = 1,
    ACTIONS(382), 1,
      anon_sym_DQUOTE,
  [1958] = 1,
    ACTIONS(384), 1,
      anon_sym_GT,
  [1962] = 1,
    ACTIONS(386), 1,
      aux_sym_string_token2,
  [1966] = 1,
    ACTIONS(388), 1,
      anon_sym_RBRACE,
  [1970] = 1,
    ACTIONS(390), 1,
      sym_identifier,
  [1974] = 1,
    ACTIONS(392), 1,
      anon_sym_GT,
  [1978] = 1,
    ACTIONS(394), 1,
      anon_sym_GT,
  [1982] = 1,
    ACTIONS(396), 1,
      aux_sym_string_token1,
  [1986] = 1,
    ACTIONS(398), 1,
      sym_identifier,
  [1990] = 1,
    ACTIONS(400), 1,
      anon_sym_GT,
  [1994] = 1,
    ACTIONS(402), 1,
      anon_sym_RBRACE,
  [1998] = 1,
    ACTIONS(404), 1,
      sym_identifier,
  [2002] = 1,
    ACTIONS(406), 1,
      anon_sym_RBRACE,
  [2006] = 1,
    ACTIONS(408), 1,
      sym_identifier,
  [2010] = 1,
    ACTIONS(410), 1,
      sym_identifier,
  [2014] = 1,
    ACTIONS(412), 1,
      sym_identifier,
  [2018] = 1,
    ACTIONS(414), 1,
      sym_identifier,
  [2022] = 1,
    ACTIONS(416), 1,
      sym_identifier,
  [2026] = 1,
    ACTIONS(418), 1,
      sym_identifier,
  [2030] = 1,
    ACTIONS(420), 1,
      sym_identifier,
  [2034] = 1,
    ACTIONS(422), 1,
      sym_identifier,
  [2038] = 1,
    ACTIONS(424), 1,
      sym_identifier,
  [2042] = 1,
    ACTIONS(426), 1,
      sym_identifier,
  [2046] = 1,
    ACTIONS(428), 1,
      sym_identifier,
  [2050] = 1,
    ACTIONS(430), 1,
      sym_identifier,
  [2054] = 1,
    ACTIONS(432), 1,
      sym_identifier,
  [2058] = 1,
    ACTIONS(434), 1,
      anon_sym_u25ca,
  [2062] = 1,
    ACTIONS(436), 1,
      aux_sym_comment_token1,
  [2066] = 1,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [2070] = 1,
    ACTIONS(438), 1,
      sym_identifier,
  [2074] = 1,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
  [2078] = 1,
    ACTIONS(440), 1,
      anon_sym_u25ca,
  [2082] = 1,
    ACTIONS(283), 1,
      anon_sym_RBRACE,
  [2086] = 1,
    ACTIONS(442), 1,
      anon_sym_EQ,
  [2090] = 1,
    ACTIONS(444), 1,
      sym_identifier,
  [2094] = 1,
    ACTIONS(446), 1,
      sym_identifier,
  [2098] = 1,
    ACTIONS(448), 1,
      anon_sym_u25ca,
  [2102] = 1,
    ACTIONS(450), 1,
      ts_builtin_sym_end,
  [2106] = 1,
    ACTIONS(452), 1,
      aux_sym_comment_token1,
  [2110] = 1,
    ACTIONS(454), 1,
      anon_sym_u25ca,
  [2114] = 1,
    ACTIONS(456), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 162,
  [SMALL_STATE(9)] = 189,
  [SMALL_STATE(10)] = 216,
  [SMALL_STATE(11)] = 243,
  [SMALL_STATE(12)] = 270,
  [SMALL_STATE(13)] = 297,
  [SMALL_STATE(14)] = 324,
  [SMALL_STATE(15)] = 351,
  [SMALL_STATE(16)] = 378,
  [SMALL_STATE(17)] = 405,
  [SMALL_STATE(18)] = 432,
  [SMALL_STATE(19)] = 459,
  [SMALL_STATE(20)] = 486,
  [SMALL_STATE(21)] = 513,
  [SMALL_STATE(22)] = 540,
  [SMALL_STATE(23)] = 567,
  [SMALL_STATE(24)] = 594,
  [SMALL_STATE(25)] = 621,
  [SMALL_STATE(26)] = 648,
  [SMALL_STATE(27)] = 675,
  [SMALL_STATE(28)] = 702,
  [SMALL_STATE(29)] = 729,
  [SMALL_STATE(30)] = 756,
  [SMALL_STATE(31)] = 783,
  [SMALL_STATE(32)] = 810,
  [SMALL_STATE(33)] = 837,
  [SMALL_STATE(34)] = 864,
  [SMALL_STATE(35)] = 891,
  [SMALL_STATE(36)] = 918,
  [SMALL_STATE(37)] = 945,
  [SMALL_STATE(38)] = 972,
  [SMALL_STATE(39)] = 999,
  [SMALL_STATE(40)] = 1026,
  [SMALL_STATE(41)] = 1053,
  [SMALL_STATE(42)] = 1080,
  [SMALL_STATE(43)] = 1107,
  [SMALL_STATE(44)] = 1125,
  [SMALL_STATE(45)] = 1143,
  [SMALL_STATE(46)] = 1161,
  [SMALL_STATE(47)] = 1181,
  [SMALL_STATE(48)] = 1190,
  [SMALL_STATE(49)] = 1199,
  [SMALL_STATE(50)] = 1208,
  [SMALL_STATE(51)] = 1219,
  [SMALL_STATE(52)] = 1228,
  [SMALL_STATE(53)] = 1239,
  [SMALL_STATE(54)] = 1250,
  [SMALL_STATE(55)] = 1259,
  [SMALL_STATE(56)] = 1268,
  [SMALL_STATE(57)] = 1277,
  [SMALL_STATE(58)] = 1288,
  [SMALL_STATE(59)] = 1299,
  [SMALL_STATE(60)] = 1308,
  [SMALL_STATE(61)] = 1319,
  [SMALL_STATE(62)] = 1330,
  [SMALL_STATE(63)] = 1339,
  [SMALL_STATE(64)] = 1348,
  [SMALL_STATE(65)] = 1357,
  [SMALL_STATE(66)] = 1366,
  [SMALL_STATE(67)] = 1377,
  [SMALL_STATE(68)] = 1386,
  [SMALL_STATE(69)] = 1397,
  [SMALL_STATE(70)] = 1406,
  [SMALL_STATE(71)] = 1417,
  [SMALL_STATE(72)] = 1428,
  [SMALL_STATE(73)] = 1437,
  [SMALL_STATE(74)] = 1446,
  [SMALL_STATE(75)] = 1455,
  [SMALL_STATE(76)] = 1464,
  [SMALL_STATE(77)] = 1473,
  [SMALL_STATE(78)] = 1482,
  [SMALL_STATE(79)] = 1491,
  [SMALL_STATE(80)] = 1500,
  [SMALL_STATE(81)] = 1509,
  [SMALL_STATE(82)] = 1520,
  [SMALL_STATE(83)] = 1529,
  [SMALL_STATE(84)] = 1540,
  [SMALL_STATE(85)] = 1549,
  [SMALL_STATE(86)] = 1558,
  [SMALL_STATE(87)] = 1567,
  [SMALL_STATE(88)] = 1576,
  [SMALL_STATE(89)] = 1585,
  [SMALL_STATE(90)] = 1594,
  [SMALL_STATE(91)] = 1603,
  [SMALL_STATE(92)] = 1612,
  [SMALL_STATE(93)] = 1621,
  [SMALL_STATE(94)] = 1630,
  [SMALL_STATE(95)] = 1639,
  [SMALL_STATE(96)] = 1648,
  [SMALL_STATE(97)] = 1657,
  [SMALL_STATE(98)] = 1666,
  [SMALL_STATE(99)] = 1675,
  [SMALL_STATE(100)] = 1689,
  [SMALL_STATE(101)] = 1703,
  [SMALL_STATE(102)] = 1717,
  [SMALL_STATE(103)] = 1731,
  [SMALL_STATE(104)] = 1745,
  [SMALL_STATE(105)] = 1759,
  [SMALL_STATE(106)] = 1773,
  [SMALL_STATE(107)] = 1787,
  [SMALL_STATE(108)] = 1801,
  [SMALL_STATE(109)] = 1815,
  [SMALL_STATE(110)] = 1829,
  [SMALL_STATE(111)] = 1843,
  [SMALL_STATE(112)] = 1857,
  [SMALL_STATE(113)] = 1870,
  [SMALL_STATE(114)] = 1878,
  [SMALL_STATE(115)] = 1886,
  [SMALL_STATE(116)] = 1890,
  [SMALL_STATE(117)] = 1894,
  [SMALL_STATE(118)] = 1898,
  [SMALL_STATE(119)] = 1902,
  [SMALL_STATE(120)] = 1906,
  [SMALL_STATE(121)] = 1910,
  [SMALL_STATE(122)] = 1914,
  [SMALL_STATE(123)] = 1918,
  [SMALL_STATE(124)] = 1922,
  [SMALL_STATE(125)] = 1926,
  [SMALL_STATE(126)] = 1930,
  [SMALL_STATE(127)] = 1934,
  [SMALL_STATE(128)] = 1938,
  [SMALL_STATE(129)] = 1942,
  [SMALL_STATE(130)] = 1946,
  [SMALL_STATE(131)] = 1950,
  [SMALL_STATE(132)] = 1954,
  [SMALL_STATE(133)] = 1958,
  [SMALL_STATE(134)] = 1962,
  [SMALL_STATE(135)] = 1966,
  [SMALL_STATE(136)] = 1970,
  [SMALL_STATE(137)] = 1974,
  [SMALL_STATE(138)] = 1978,
  [SMALL_STATE(139)] = 1982,
  [SMALL_STATE(140)] = 1986,
  [SMALL_STATE(141)] = 1990,
  [SMALL_STATE(142)] = 1994,
  [SMALL_STATE(143)] = 1998,
  [SMALL_STATE(144)] = 2002,
  [SMALL_STATE(145)] = 2006,
  [SMALL_STATE(146)] = 2010,
  [SMALL_STATE(147)] = 2014,
  [SMALL_STATE(148)] = 2018,
  [SMALL_STATE(149)] = 2022,
  [SMALL_STATE(150)] = 2026,
  [SMALL_STATE(151)] = 2030,
  [SMALL_STATE(152)] = 2034,
  [SMALL_STATE(153)] = 2038,
  [SMALL_STATE(154)] = 2042,
  [SMALL_STATE(155)] = 2046,
  [SMALL_STATE(156)] = 2050,
  [SMALL_STATE(157)] = 2054,
  [SMALL_STATE(158)] = 2058,
  [SMALL_STATE(159)] = 2062,
  [SMALL_STATE(160)] = 2066,
  [SMALL_STATE(161)] = 2070,
  [SMALL_STATE(162)] = 2074,
  [SMALL_STATE(163)] = 2078,
  [SMALL_STATE(164)] = 2082,
  [SMALL_STATE(165)] = 2086,
  [SMALL_STATE(166)] = 2090,
  [SMALL_STATE(167)] = 2094,
  [SMALL_STATE(168)] = 2098,
  [SMALL_STATE(169)] = 2102,
  [SMALL_STATE(170)] = 2106,
  [SMALL_STATE(171)] = 2110,
  [SMALL_STATE(172)] = 2114,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(167),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(172),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(171),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(170),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(148),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(163),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(153),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(168),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(130),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(143),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(156),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(136),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(158),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(159),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(155),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(152),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(151),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(148),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(163),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(167),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(172),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(171),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(170),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(153),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(168),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(160),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(161),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(150),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(147),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(162),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(146),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(145),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(164),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(143),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(136),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(158),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(159),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(157),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 1, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 1, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 7, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_args, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_args, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_args, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_args, 2, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 8, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 8, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_args, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_args, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3, 1, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 1, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lozenge_command, 5, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lozenge_command, 5, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 7, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lozenge_command, 4, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lozenge_command, 4, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_args, 3, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_args, 3, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(165),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [293] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [319] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(165),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [344] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [348] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [446] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [448] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [450] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [452] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [456] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pollen(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
